apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: tic-tac
  namespace: argocd
spec: 
  destination:
    namespace: default
    server: "https://kubernetes.default.svc"
  project: tic-tac
  source: 
    path: <<<path of the k8s manifest>>>
    repoURL: <<<Repo url>>>
    targetRevision: <Branch>>>
    directory:
      recurse: true
  syncPolicy:
    automated:   
      prune: true  
      selfHeal: true 
    syncOptions:
      - CreateNamespace=true

    